apiVersion: batch/v1
kind: Job
metadata:
  name: oras-copy-job
spec:
  template:
    spec:
      containers:
      - name: oras-copy-knowledge
        image: ghcr.io/oras-project/oras:v1.2.0
        command: ["oras", "pull", "registry.redhat.io/rhelai1/knowledge-adapter-v3@sha256:ef1608ec78d5e39655b505544c0f30a015a6c9cb7e2b2deffe394791f8c76c6f", "--output", "/mnt/knowledge", "--registry-config", "/workspace/.docker"]
        volumeMounts:
        - name: docker-config
          mountPath: /workspace/.docker
          subPath: .dockerconfigjson  # Mount the Docker config as config.json
        - name: model-pvc
          mountPath: /mnt
      - name: oras-copy-skills
        image: ghcr.io/oras-project/oras:v1.2.0
        command: ["oras", "pull", "registry.redhat.io/rhelai1/skills-adapter-v3@sha256:53dd11a762bb39fc33c15499891309f0cdc8dbfd02abf94c9c60aad643aca255", "--output", "/mnt/skills", "--registry-config", "/workspace/.docker"]
        volumeMounts:
        - name: docker-config
          mountPath: /workspace/.docker
          subPath: .dockerconfigjson  # Mount the Docker config as config.json
        - name: model-pvc
          mountPath: /mnt
      - name: oras-copy-model
        image: ghcr.io/oras-project/oras:v1.2.0
        command: ["oras", "pull", "registry.redhat.io/rhelai1/mixtral-8x7b-instruct-v0-1@sha256:bc08e466aa35352a621d0ad221c2e247ff9751f4cb6cffe00d5894ce6bfd3fd7", "--output", "/mnt/model", "--registry-config", "/workspace/.docker"]
        volumeMounts:
        - name: docker-config
          mountPath: /workspace/.docker
          subPath: .dockerconfigjson  # Mount the Docker config as config.json
        - name: model-pvc
          mountPath: /mnt
      restartPolicy: Never
      volumes:
      - name: model-pvc
        persistentVolumeClaim:
          claimName: mixtral-serving-ilab
      - name: docker-config
        secret:
          secretName: 7033380-ilab-pull-secret
  backoffLimit: 4
